require("telescope").load_extension("harpoon")

vim.keymap.set("n", "<leader>Ha", function()
	require("harpoon.mark").add_file()
end, { desc = "[H]arpoon [A]dd File" })
vim.keymap.set("n", "<leader>Hr", function()
	require("harpoon.mark").remove_file()
end, { desc = "[H]arpoon [R]emove File" })
vim.keymap.set("n", "<leader>Hs", "<cmd>Telescope harpoon marks<cr>", { desc = "[H]arpoon [S]search" })
vim.keymap.set("n", "<leader>sh", "<cmd>Telescope harpoon marks<cr>", { desc = "[S]search [H]arpoon" })
vim.keymap.set("n", "<leader>Hl", function()
	require("harpoon.ui").toggle_quick_menu()
end, { desc = "[H]arpoon [L]ist" })
vim.keymap.set("n", "<leader>H1", function()
	require("harpoon.ui").nav_file(1)
end, { desc = "[H]arpoon Goto File [1]" })
vim.keymap.set("n", "<leader>H2", function()
	require("harpoon.ui").nav_file(2)
end, { desc = "[H]arpoon Goto File [2]" })
vim.keymap.set("n", "<leader>H3", function()
	require("harpoon.ui").nav_file(3)
end, { desc = "[H]arpoon Goto File [3]" })
vim.keymap.set("n", "<leader>H4", function()
	require("harpoon.ui").nav_file(4)
end, { desc = "[H]arpoon Goto File [4]" })
